CREATE TABLE YEEPAY_WITHDRAW_BATCH (
  ID                  BIGINT          PRIMARY KEY AUTO_INCREMENT,
  BATCH_NO            VARCHAR(16)     UNIQUE NOT NULL,
  CREATED_AT          DATETIME        NOT NULL,
  SENT_TOTAL_AMT      NUMERIC(15, 2)  NOT NULL,
  SENT_TOTAL_NUM      SMALLINT        NOT NULL,
  SUCCESS_TOTAL_AMT   NUMERIC(15, 2),
  SUCCESS_TOTAL_NUM   SMALLINT,
  SYSTEM_CODE         VARCHAR(16)     NOT NULL DEFAULT '',
  SYSTEM_MESSAGE      VARCHAR(128)    NOT NULL DEFAULT '',
  STATUS_CODE         VARCHAR(16)     NOT NULL DEFAULT ''
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE YEEPAY_WITHDRAW_ORDER (
  ID              BIGINT          PRIMARY KEY AUTO_INCREMENT,
  BATCH_NO        VARCHAR(16),
  ORDER_ID        VARCHAR(64)     NOT NULL,
  CREATED_AT      DATETIME        NOT NULL,
  BANK_CODE       VARCHAR(16)     NOT NULL,
  BANK_NO         VARCHAR(32)     NOT NULL,
  AMOUNT          NUMERIC(15, 2)  NOT NULL,
  USER_NAME       VARCHAR(16)     NOT NULL,
  USER_ID         VARCHAR(64)     NOT NULL,
  SENT_STATUS     VARCHAR(16)     NOT NULL,
  SENT_MESSAGE    VARCHAR(128)    NOT NULL DEFAULT '',
  SENT_AT         DATETIME,
  OFFER_STATUS    VARCHAR(16)     NOT NULL,
  OFFER_MESSAGE   VARCHAR(128)    NOT NULL DEFAULT '',
  OFFER_AT        DATETIME,

  FOREIGN KEY (BATCH_NO) REFERENCES YEEPAY_WITHDRAW_BATCH(BATCH_NO)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;